services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - app-pgdb:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

volumes:
  app-pgdb: